version: '3.9'

services:
  npm:
    image: node:lts-alpine
    container_name: joomlagov-npm
    profiles:
      - dev
    ports:
      - '3000:3000'
      - '3001:3001'
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    entrypoint: [npm]
    command: run dev
    environment:
      GULP_HOST: webapp
    depends_on:
      - webapp
    networks:
      - webapp

  webapp:
    container_name: joomlagov-webapp
    profiles:
      - dev
    volumes:
      - .docker/php/configuration.php:/docker-entrypoint.d/configuration.php
      - ./:/var/www/html
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST}
      JOOMLA_DB_USER: ${JOOMLA_DB_USER}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD}
      JOOMLA_DB_NAME: ${JOOMLA_DB_NAME}
      JOOMLA_DB_PREFIX: ${JOOMLA_DB_PREFIX}
      JOOMLA_ROOT_USERNAME: ${JOOMLA_ROOT_USERNAME}
      JOOMLA_ROOT_PASSWORD: ${JOOMLA_ROOT_PASSWORD}
    networks:
      - webapp
